<?php

    /* common */

    define('ZERO_OF_1_PAGES', 'Page {0} sur {1}');
    define('ZERO_1_OF_2_ICONS', '{0} - {1} icone sur {2} ');
    define('ADD_NEW_ITEM', 'Ajouter un élémént');
    define('ALERT_STYLE', 'Style');
    define('ALERT_TEXT', 'Alerte');
    define('APPEND', 'Après');
    define('BADGE_TEXT', 'Texte');
    define('BREAKPOINT', 'Point de rupture');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_DEVICES', 'Les blocs seront superposés sur les petits supports (smartphones)');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_SMALL_DEVICES', 'Les blocs seront superposés sur les supports très petits et petits (smartphones &amp; petites tablettes)');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_SMALL_MEDIUM_DEVICES', 'Les blocs seront superposés sur les supports très petits, petits et moyens (smartphones &amp; tablettes)');
    define('BLOCKS_WILL_NEVER_BE_STACKED', 'Les blocs ne seront jamais superposés');
    define('BUTTON_SIZE', 'Taille');
    define('BUTTON_STYLE', 'Style');
    define('CELLS', 'Cellules');
    define('CENTER', 'CENTRER');
    define('CLOSE_BUTTON', 'BOUTON FERMER');
    define('CODE', 'Code');
    define('COLOR', 'Couleur');
    define('COLS', 'Colonnes');
    define('CONTENT', 'Contenu');
    define('CURRENT', 'Page courante');
    define('CUSTOM', 'Personnalisé');
    define('DELETE_CONST', 'Supprimer');
    define('DELETE_THIS_ITEM', 'Supprimer cet élément');
    define('DISABLED', 'Désactivé');
    define('DISABLED_ELEMENTS_WILL_NOT_BE_EDITABLE_IN_TINYMCE_EDITOR', 'Les éléments désactivés ne seront pas éditables dans tinymce');
    define('DRAG_DROP_ELEMENTS_TO_PREVIEW', 'Glissez-déposez les éléments pour prévisualiser');
    define('DROP_ELEMENTS_HERE', 'Déposez les éléments ici');
    define('FOOTER', 'AVEC FOOTER');
    define('FOOTER_CONTENT', 'Contenu du footer');
    define('HEADING', 'AVEC ENTETE');
    define('DISMISSABLE', 'Bouton fermer');
    define('HEADING_CONTENT', 'Contenu de l\'entête');
    define('HORIZONTAL_HEADER', 'Entête horizontale');
    define('HTML_AUTHORIZED', 'HTML autorisé');
    define('ICON', 'Icone');
    define('ICON_SIZE', 'Taille');
    define('ITEMS', 'Eléments');
    define('LABEL_STYLE', 'Style');
    define('LABEL_TEXT', 'Texte');
    define('LINK', 'Lien');
    define('MAIN_CONTENT', 'Contenu principal');
    define('MY_FANTASTIC_BUTTON', 'Ce bouton est extraordinaire');
    define('NEW_CONST', 'Nouveau');
    define('NEW_ITEM', 'Nouvel élément');
    define('NEXT', 'Suivant');
    define('NO', 'NON');
    define('NO_CLOSE_BUTTON', 'SANS BOUTON FERMER');
    define('NO_FOOTER', 'SANS FOOTER');
    define('NO_HEADING', 'SANS ENTETE');
    define('OTHERS', 'Autres');
    define('PANEL_CONTENT', 'Contenu');
    define('PANEL_STYLE', 'Panel style');
    define('PANEL_TITLE', 'Titre');
    define('POSITION', 'Position');
    define('PREPEND', 'Avant');
    define('PREVIEW', 'Aperçu');
    define('PREVIOUS', 'Précédent');
    define('PUSH_TO_THE_SIDES', 'ALIGNER SUR LES BORDS');
    define('ROWS_COLS', 'Lignes/colonnes');
    define('ROW_COL_EDITION_IS_DISABLED_FOR_EDITED_TABLES', 'L\\\'édition des lignes/colonnes de tableaux est désactivée.<br>Vous pouvez facilement ajouter/supprimer des lignes/colonnes directement depuis tinymce.');
    define('SECTIONS', 'Sections');
    define('SIZE', 'Taille');
    define('STRUCTURE', 'Structure');
    define('STYLE', 'Style');
    define('TAG', 'Balise');
    define('TEXT', 'Texte');
    define('TITLE', 'Titre');
    define('VALUE', 'Valeur');
    define('VERTICAL_HEADER', 'Entête verticale');
    define('WIDTH', 'Largeur');
    define('YES', 'OUI');
    define('YOUR_TEXT', 'Votre texte');
